version: '3.9'
services:
  metabase:
    build: metabase
    container_name: metabase
    hostname: metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    networks:
      - metanet1
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: pgpassword123
    ports:
      - 5432:5432
    networks:
      - metanet1
networks:
  metanet1:
    driver: bridge
